### ISSUE TITLE
Works only with Doctrine?

### ISSUE THREAD

**Issue by utrenkner** [Eye4web/Eye4webZfcUserForgotPassword#2]
My project does not use Doctrine so far. Error-messages hinted me at installing doctrine/doctrine-orm-module. However, this does not suffice apparently:
''' PHP Fatal error:  Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'An alias "Doctrine\ORM\EntityManager" was requested but no service could be found.' in /usr/local/(...)/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:549'''
Would I have to switch everything to Doctrine ORM to get Eye4webZfcUserForgotPassword
working?

Thanks for any tipps!

**Comment by Danielss89** [comment]
Yes, so far, this module only has an adapter for Doctrine. You can create your own db mapper for Zend\Db though. Shouldn't be too hard. Look at the DoctrineORMMapper.

**Comment by utrenkner** [comment]
Thanks. In the end I chose to go the Doctrine way. It seems to work perfectly, now. Many thanks for providing this module under a permissive license (MIT)!
